# Using JMeter with ActiveMQ Artemis

JMeter can interact with a message broker via JMS. It requires a JNDI InitialContext to read connection parameters as it used to be with J2EE application servers. Artemis being a standalone message broker doesn't provide a JNDI service, but related client libraries has InitialContextFactory implementations that we can use to create a "mock" JNDI Context required by the JMeter samplers.

We can choose between the following Java clients (and the included _InitialContextFactory_) to connect to the broker:

* Artemis Core client
* Qpid AMQP client

The InitialContextFactory implementations in these client libraries have some differences that we need to understand before trying to use them in JMeter samplers. (This will make more sense when we look at the JMeter side)

We need to add the cient jar files from `$ARTEMIS_HOME/lib` to JMeter's classpath. Simply copy these file to `$JMETER_HOME/lib` (or maybe use the _user.classpath_ property):

* Artemis Core client: _artemis-jms-client-all-x.z.y.jar_
* Qpid AMQP client: _qpid-jms-client-x.y.z.jar_ and _proton-j-x.y.z.jar_

## Artemis Core client

Java client for Artmeis Core protocol with _org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory_ JDNI Context:

* Documentation: http://activemq.apache.org/components/artemis/documentation/latest/using-jms.html
* Source: https://github.com/apache/activemq-artemis/blob/master/artemis-jms-client/src/main/java/org/apache/activemq/artemis/jndi/ActiveMQInitialContextFactory.java

The JNDI property naming convention for _org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory_:

* The connection url for the broker should be set in a JNDI property matching the connection factory lookup name with the `connectionFactory.` prefix. For example as `connectionFactory.myFactoryLookupName=tcp://localhost:61616`. The accepted protocols are _tcp://_, _udp://_, _vm://_, _jgroups://_ (I only tried _tcp_).
* The queue or topic name on the broker side should be set as JNDI property with _queue._ or _topic._ prefix. For example `queue.myDestinationLookupName=myqueue` or `topic.myDestinationLookupName=mytopic`. 
* As this the queue/topic lookup logic adds an extra layer of complexity, the class supports _dynamicQueues/_ and _dynamicTopics/_ prefixes where we simply can add the name of the queue or tpoic on the broker and we don't need to set the _queue._ or _topic._ JNDI properties at all. To connect to _myqueue_ on the broker we can just use `dynamicQueues/myqueue` as the destination lookup name in the samplers.

Surprisingly if the Provider URL (or _java.naming.provider.url_ property) is set, it's parsed as a broker connection url - instead of a JNDI provider endpoint - by the _ActiveMQInitialContextFactory_  and it's added to the JNDI context as `ConnectionFactory` lookup name, see the later how this feature (?) can be utilized.

## Qpid AMQP client

The Qpid AMQP Java client has the class _org.apache.qpid.jms.jndi.JmsInitialContextFactory_ for JNDI Context support.

* Documentation: https://qpid.apache.org/releases/qpid-jms-0.54.0/docs/index.html
* Source: https://github.com/apache/qpid-jms/blob/master/qpid-jms-client/src/main/java/org/apache/qpid/jms/jndi/JmsInitialContextFactory.java

The JNDI property naming convention for _org.apache.qpid.jms.jndi.JmsInitialContextFactory_:

* The connection url for the broker should be set in a JNDI property matching the connection factory lookup name with the `connectionfactory.` prefix. For example as `connectionfactory.myFactoryLookupName=amqp://localhost:5672`. The accepted protocols are _amqp://_, _amqps://_, _amqpws://_, _amqpwss://_.
* Setting queue or topic name is the same as for _ActiveMQInitialContextFactory_. Use JNDI properties with _queue._ or _topic._ prefix. For example `queue.myDestinationLookupName=myqueue` or `topic.myDestinationLookupName=mytopic`. 
* This InitialContextFactory also supports _dynamicQueues/_ and _dynamicTopics/_ prefixes, so we don't need to set the JDNI properties for destination names. For example `_dynamicQueues/myqueue_`.

If the Provider URL (or _java.naming.provider.url_ property) is set, a file url or path is expected that will be parsed instead of the _jndi.properties_ on the classpath. This is an important difference compared to _ActiveMQInitialContextFactory_.

// To interact with a queue or a topic JMeter will do a JNDI lookup for a destination so we need a JDNI parameter respectively with _queue._ or _topic._ prefix (prefix is case insensitive). This prefix will also decide if the destination will be expected as a queue or a topic. If we want to use a queue called "myqueue" on the broker we need an JNDI property _queue.myDestinationLookupName=myqueue_ or in case of a topic _topic.myDestinationLookupName=mytopic_. The destination name _myDestinationLookupName_ must be used in the JMeter semplers. 

// As this the lookup logic add an extra layer of complexity the class supports _dynamicQueues/_ and _dynamicTopics/_ prefixes where we simply can add the name of the queue or tpoic on the broker and we don't need to add the JNDI parameters. To connect to "myqueue" on the broker we can just use _dynamicQueues/myqueue_ as the destination lookup name in the samplers. 

Let's see how we can use these clients in JMS samplers.

## JMS Point-to-point 
This sampler works for queues only. It has a nice a JNDI Properties table on GUI, so we don't need to edit a _jndi.properties_ file. 
TODO: Check for Topics?

*Artemis Core client*
Set fields as:

* _Initial Context Factory_: `org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory`. 
* _QueueConnection Factory_: lookup name (e.g. `MyConnectionFactory`). Add the broker url to the JNDI properties table _connectionFactory.MyConnectionFactory=tcp://localhost:61616_. (Alternatively the broker url can be set as _Provider URL_ with lookup name `ConnectionFactory`)
* The queue name should be stored in a JNDI property _queue.mylookupname=myqueue_ and `mylookupname` is set as _JNDI name Request/Receive queue_. Or we can use looukp name _dynamicQueues/myqueue_ so we can skip the queue JNDI property.

[TODO] image

*Artemis Core client*
Set JNDI _Initial Context Factory_ to _org.apache.qpid.jms.jndi.JmsInitialContextFactory_. Use any _QueueConnection Factory_ lookup name (e.g. MyConnectionFactory) and add the connection url to the JNDI properties table _connectionfactory.MyConnectionFactory=amqp://artemishost:5672_. The queue name should be stored in a JNDI property _queue.mylookupname=myqueue_ and "mylookupname" is set as _JNDI name Request/Receive queue_. Or we can set _dynamicQueues/myqueue_ as JNDI name so we don't need the _queue.lookupname_ property.

[TODO] image


[NOTE]
====
Note: For both protocols the authentication username/password can be set in the usual _java.naming.security.principal_ and _java.naming.security.credentials_ JNDI properties.
====

## JMS Publisher
Can send messages to queues and topics too. It has no generic JNDI propeties table, but it comes with connection parameter fields instead. First follow the easy path and try to use JMeter GUI only

*Artemis Core client*

Because of the beforementioned feature of _org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory_ using the _Provider URL_ as broker connection string it's possible to configure simple scenarios without using _jndi.properties_ file. Set fields as:

* _Initial Context Factory_: `org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory`
* _Provider URL_: `tcp://artemis_host:61616`
* _Connection Factory_: _ConnectionFactory_.
* Username and password if _Use Authorization?_ is required. 
* _Destination_ to _dynamicQueues/myqueue_ (so we can skip the queue lookup JNDI properties).

*Qpid AMQP client*
The challange with _org.apache.qpid.jms.jndi.JmsInitialContextFactory_ is to set the broker connection url, we can't set this only through the GUI, we'll need a _jndi.properties_ file for that. This InitialContextFactory tries to parse the file url or path set in the _Provider URL_ field as a _jndi.properties_ file so we don't have to add that file to classpath. Simply leave the _Use jndi.properties file_ unchecked and set _Provider URL_ to the location of our custom file (e.g. /tmp/myjndi.properties) and set _connectionfactory.myConnectionFactory=amqp://localhost:5672_ while _Connection Factory_ field refers that lookup name (myConnectionFactory).

## Using jndi.properties

In the examples above we - mostly - avoided creating a _jndi.properties_ file and adding it to the classpath. Let's try that approach instead of being dependent on the parameters of the samplers.
A text file can be added to the classpath by packaging it into a jar file and adding the jar file to the classpath:

* Create a file called _jndi.properties_
* Package it into a jar 

  jar -cf my-jndi-properties.jar jndi.properties

* Add to JMeter's classpath by one of the following ways:
** Drop the jar in the `lib` directory:

   cp my-jndi-properties.jar $JMETER_HOME/lib/

** Add `user.classpath` entry to `$JMETER_HOME/bin/user.properties` (or `$JMETER_HOME/bin/system.properties`):

   user.classpath=/path/my-jndi-properties.jar

** Add `user.classpath` as JMeter user property via the command line:

   jmeter.sh -Juser.classpath=/path/my-jndi-properties.jar

** Add `user.classpath` as Java system property via an env var:

   export JMETER_OPTS=-Duser.classpath=/path/my-jndi-properties.jar

The jndi.properties should look like something like this:
```
# Using AMQP protocol
java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
connectionfactory.myConnectionFactory=amqp://localhost:5672

# Using Artemis Core protocol
#java.naming.factory.initial=org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory
#connectionFactory.myConnectionFactory=amqp://localhost:5672

java.naming.security.principal=amq
java.naming.security.credentials=secret
queue.myqueue=q1
topic.mytopic=t1
```
In the samplers we only need to set the lookup name for the ConnectionFactory (`myConnectionFactory`) and the Queue/Topic (`myqueue`) - or we can use _dynamicQueues/_ prefix. In _JMS Publisher/Subscriber_ enable _Use jndi.properties file_.


### How to use _jndi.properties_ without a jar?
Unfortunately I'm not aware of a solution to add the _jndi.properties_ to the JMeter classpath without packaging it in a jar file.  Setting all properties as Java system properties - passed in the command line or `$JMETER_HOME/bin/system.properties` - doesn't work.

As long as we'd like to use AMQP protocol `org.apache.qpid.jms.jndi.JmsInitialContextFactory` we can set the Provider URL `java.naming.provider.url` point to our _jndi.properties_ file:
`export JMETER_OPTS='-Djava.naming.provider.url=/Users/bszeti/tmp/amq/jmeter/my-jndi.properties -Djava.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory'`
This doesn't work with org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory as it expects a broker url in _java.naming.provider.url_.

// For example:
// ```
// export JMETER_OPTS="\
// -Djava.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory \
// -Dconnectionfactory.myConnectionFactory=amqp://localhost:5672
// -Djava.naming.security.principal=amq \
// -Djava.naming.security.credentials=secret \
// -Dqueue.myqueue=q1"
// ```

// export JMETER_OPTS="\
// -Djava.naming.factory.initial=org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory \
// -Djava.naming.provider.url=tcp://localhost:61616
// -Djava.naming.security.principal=amq \
// -Djava.naming.security.credentials=secret \
// -Dqueue.myqueue=q1"




// Relative path is from current directory:
// export JMETER_OPTS='-Djava.naming.provider.url=../../projects/UPSFreight/git/jmeter-artemis-test/jndi.properties -Djava.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory'



// export JMETER_OPTS='-Djava.naming.provider.url=/Users/bszeti/projects/UPSFreight/git/jmeter-artemis-test/jndi.properties -Djava.naming.factory.initial=org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory'